---
- name: run umami and postgres on docker for production enviroment
  hosts: umami_host
  become: yes  
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600 

   roles:
    - docker_setup
    - umami_deploy
    - git_setup
    - cron_job_setup
