---
- name: Update yum repositories
  yum:
    name: '*'
    state: latest

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Remove outdated Docker packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent  # This will remove the packages

- name: Add Docker repository
  become: yes  
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install latest Docker packages
  become: yes  # To execute the task with sudo privileges
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present  # This will ensure the packages are installed
    
- name: Install docker-compose-plugin
  yum:
    name: docker-compose-plugin
    state: present

- name: Start Docker Daemon
  systemd:
    state: started
    enabled: yes
    name: docker
