---
- name: Run docker-compose up
  command: docker compose up -d
  become: yes
  args:
    chdir: ./umami_prod/docker_cont

- name: Run commands inside Docker container
  command: docker exec -t postgres_DB /bin/bash -c "su - postgres -c 'sed -i s/trust/md5/g /var/lib/postgresql/data/pg_hba.conf && cd /var/lib/postgresql/data && pg_ctl reload -D .'"
