---
version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-v1.33.2
    container_name: umami
    ports:
      - "8080:3000"
    
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}

    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:15-alpine
    container_name: postgres_DB
    environment:
      - POSTGRES_DB: umami
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - umami-db-data:/var/lib/postgresql/data
      - ./init-backup_user.sql:/docker-entrypoint-initdb.d/init_backup_user.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:
  init-scripts:
    driver: local